addons:
  ssh_known_hosts: russellhay.com
language: go
go:
- tip
install: go get -v github.com/spf13/hugo
script:
- mkdir -p themes/doomsparkle/static/css/
- sass themes/doomsparkle/sass/main.scss:themes/stainless/static/css/main.css --style
  compressed
- hugo
notifications:
  email:
    on_faliure: always
before_install:
- openssl aes-256-cbc -K $encrypted_62d72ab54bb9_key -iv $encrypted_62d72ab54bb9_iv
  -in doomsparkle-deploy.enc -out doomsparkle-deploy -d
- gem install sass
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/doomsparkle-deploy
- ssh-add $TRAVIS_BUILD_DIR/doomsparkle-deploy
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet $TRAVIS_BUILD_DIR/public/ deploy@russellhay.com:/home/www/doomsparkle/
  on:
    branch: master
